### ISSUE TITLE
导出排班表后是customization后缀而不是json

### ISSUE THREAD

**Issue by JianXian57** [Arknights-yituliu/frontend-v2-plus#107]
<img width="217" alt="1735376017075" src="https://github.com/user-attachments/assets/219c66ad-2c8e-414a-8c6d-eb91d69da744" />

MAA无法直接识别该文件，直接改后缀为json后MAA可以识别，但直接运行完成。

**Comment by yamasakura** [comment]
你是用的校园网之类的网络吗？

**Comment by JianXian57** [comment]
不是，经提醒使用流量试了一下也不行

**Comment by JianXian57** [comment]
> 你是用的校园网之类的网络吗？

不是，经提醒使用流量试了一下也不行

**Comment by yamasakura** [comment]
那有点难办，目前就有部分是切出校园网成功了，没搞明白造成这个问题的具体原因是什么，我问问其他开发

**Comment by JianXian57** [comment]
> 那有点难办，目前就有部分是切出校园网成功了，没搞明白造成这个问题的具体原因是什么，我问问其他开发

好的，我去找其他朋友帮忙生成下吧

**Comment by JianXian57** [comment]
> 那有点难办，目前就有部分是切出校园网成功了，没搞明白造成这个问题的具体原因是什么，我问问其他开发

非常之奇怪。现已解决。
1.奇怪之处1：使用手机登录一图流网站，利用ID导入后进行下载。在安卓使用夸克浏览器、X浏览器仍无法正常下载，使用IQOO手机自带的浏览器下载出了JSON格式。
2.奇怪之处2：MAA导入后尝试执行，不到8s显示完成→尝试导入MAA自带的排班表进行测试，成功→再次执行自带的，失败→导入自制排版表执行，失败→再次执行自制的排班表，成功。现已正常使用。

**Comment by JianXian57** [comment]
谢谢帮助
