### ISSUE TITLE
小建议或者小的基建排班想法

### ISSUE THREAD

**Issue by feiqingbiss** [Arknights-yituliu/frontend-v2-plus#18]
森空岛的数据已经可以抓取了，干员的练度也可以知道了，那么是不是可以联动基建排班表这个功能做个一键最优排班呢，不知道这个能不能实现，懒，但是打赏~

**Comment by yamasakura** [comment]
暂时不太行，讨论了一下暂时没法处理复杂的基建套组，比如迷迭香宇宙等
