### ISSUE TITLE
基建排班表测试版体验

### ISSUE THREAD

**Issue by miyuanaa** [Arknights-yituliu/frontend-v2-plus#24]
测试版布局可视化，但是排班表基建房间编号是顺序排列，而在游戏中并不是这样，比如排版表1号贸易站，在我游戏里是第一行第二个。我尝试拆除重建了一个错位的制造站，没能改变游戏内编号。
这个问题造成了排班表可视化了，但跟游戏内仍是错位的，当然整体毕竟是排好班了，能用，只是顺序错位，不知能否优化，或者游戏内有没有改变编号方法。

**Comment by yamasakura** [comment]
游戏内编号比较蛋疼，每行从右到左排序，比如第一行有俩个站，按正常阅读顺序分别是从左到右是2，1号。
而maa执行根据序号来换班，所以这个没啥好办法，他不是识别基建的位置。
所以排班要根据下面这个页面去排
![111](https://github.com/Arknights-yituliu/frontend-v2-plus/assets/84258011/e5dc565e-b3e8-469e-a518-75249f3459d0)
尽管生成器可以按游戏布局去生成，但是实际上还是要按编号去执行。
尝试按游戏布局会看着排序怪了点
会变成  

制造站#1
制造站#3  制造站#2
制造站#5  制造站#4

这样的布局

所以暂时没想到好的解决办法

**Comment by Acid-or** [comment]
在排班表中选择时间07：30-23：29，导出得到如下排班：
![image](https://github.com/Arknights-yituliu/frontend-v2-plus/assets/156598710/27a5451f-578c-4829-8e48-d1048cd7e13f)
"id": 1702203342688921

**Comment by yamasakura** [comment]
> 在排班表中选择时间07：30-23：29，导出得到如下排班： ![image](https://private-user-images.githubusercontent.com/156598710/296586002-27a5451f-578c-4829-8e48-d1048cd7e13f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyODM2MzMsIm5iZiI6MTcwNTI4MzMzMywicGF0aCI6Ii8xNTY1OTg3MTAvMjk2NTg2MDAyLTI3YTU0NTFmLTU3OGMtNDgyOS04ZTQ4LWQxMDQ4Y2Q3ZTEzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwMTQ4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hM2NmMGFhOTBlZTYxODFmNDRlM2RiNjAwODg1Y2I4MDQyMzQ4MDVmNGQxNDBmMWRjY2ViZDE4ZTljMzEzNDc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tVaVafwq6sYLcgoB3ztVtQC4ntTjjYgHIeD7qczQx8o) "id": 1702203342688921
应该是判断跨天出问题了，我去改一下判定

**Comment by yamasakura** [comment]
> 在排班表中选择时间07：30-23：29，导出得到如下排班： ![image](https://private-user-images.githubusercontent.com/156598710/296586002-27a5451f-578c-4829-8e48-d1048cd7e13f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyODM3NzQsIm5iZiI6MTcwNTI4MzQ3NCwicGF0aCI6Ii8xNTY1OTg3MTAvMjk2NTg2MDAyLTI3YTU0NTFmLTU3OGMtNDgyOS04ZTQ4LWQxMDQ4Y2Q3ZTEzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwMTUxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NWE1ZjA1OGI3ZDE5MmFlYWQxMDFkZjM4MmRmNmM1MTMyYWNmMTU1YTgxMWIwNTU1ZmVhYjgzODNhNjIxZGQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KGGat8ivjP31Zvgnn9Tv_GFzEjFblgMPiZeZ12mnxk8) "id": 1702203342688921



跨天判定出问题了，我一会看看

**Comment by miyuanaa** [comment]
> 游戏内编号比较蛋疼，每行从右到左排序，比如第一行有俩个站，按正常阅读顺序分别是从左到右是2，1号。 而maa执行根据序号来换班，他不是识别基建的位置。 所以排班要根据下面这个页面去排 ![111](https://private-user-images.githubusercontent.com/84258011/296535363-e5dc565e-b3e8-469e-a518-75249f3459d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNzU1OTQsIm5iZiI6MTcwNTI3NTI5NCwicGF0aCI6Ii84NDI1ODAxMS8yOTY1MzUzNjMtZTVkYzU2NWUtYjNlOC00NjllLWE1MTgtNzUyNDlmMzQ1OWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDIzMzQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3N2M3MTYxNjUzODZhYzQ1YTk4NWI1ZjdhYjkwZjg4NDkwMmNjOGQ5M2ZlMDE1MzdmZTBkMDhkYTY2ZTE0NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5n6ViuWDG3AL_vdHXnmSlIO4KwlF3k2T2iX4H-VK5mA) 尽管生成器可以按游戏布局去生成，但是实际上还是要按编号去执行。 尝试按游戏布局会看着排序怪了点 会变成
> 
> 制造站#1 制造站#3 制造站#2 制造站#5 制造站#4
> 
> 这样的布局
> 
> 所以暂时没想到好的解决办法

了解了，好吧。但其实我游戏里好像也不全是从右向左
贸易2 贸易1 制造1
制造3 制造4 制造2
很怪，不知道为啥
