### ISSUE TITLE
关于排班表生成器内显示干员技能和点击选取干员的建议

### ISSUE THREAD

**Issue by Private233** [Arknights-yituliu/frontend-v2-plus#27]
在选干员入驻基建的时候，往往想看两眼干员的基建技能以便更好进行比较或确定最优选，按现在样式来看我觉得可以在下方显示已入驻当前房间的干员的技能。（文本量感觉也挺大的，辛苦大大们考虑考虑）
另外还有个，对于干员选取或取消，能否都做在点击干员头像上，就是点一次干员是选择，再点一次干员就取消选择，目前的模式是在下面干员头像上点击选择，取消则要在上方的当前房间内点干员头像角落的小叉（或者上下两边都可以点击以取消？）

**Comment by yamasakura** [comment]
可以显示，就是不好找地方显示，你看看哪里适合加？截个图标注一下，我回头看看

**Comment by yamasakura** [comment]
这个删除图标主要是提示可以删除，或者可以加个提示，再次点击头像删除，然后把点击事件绑定到整个头像

**Comment by Private233** [comment]
![image](https://github.com/Arknights-yituliu/frontend-v2-plus/assets/108540840/71f96921-f0f2-40bb-8940-2ba473344a10)
![image](https://github.com/Arknights-yituliu/frontend-v2-plus/assets/108540840/9bd15278-47de-4d88-ba5f-a91eaa0cd29d)
参考了一下工具箱的排版，大致这样的板块大小感觉确实没有什么好地方可以放的，感觉还是就在最下面多扩展一点来显示吧

**Comment by yamasakura** [comment]
> ![image](https://private-user-images.githubusercontent.com/108540840/299885830-71f96921-f0f2-40bb-8940-2ba473344a10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MjQ4ODgsIm5iZiI6MTcwNjQyNDU4OCwicGF0aCI6Ii8xMDg1NDA4NDAvMjk5ODg1ODMwLTcxZjk2OTIxLWYwZjItNDBiYi04OTQwLTJiYTQ3MzM0NGExMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQwNjQ5NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTRkNGQ4MmNiNjMyMWQyNmM2NGRmNmI5NmYyMjgwNzVhMDI2ODg1MjI2Nzc0NWExZGFiMmMyMDg3YWMxYmJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FCuIsojxmPfY7HPDuvk4kjO4ORR5PCjWMGh09qxpH3E) ![image](https://private-user-images.githubusercontent.com/108540840/299885949-9bd15278-47de-4d88-ba5f-a91eaa0cd29d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MjQ4ODgsIm5iZiI6MTcwNjQyNDU4OCwicGF0aCI6Ii8xMDg1NDA4NDAvMjk5ODg1OTQ5LTliZDE1Mjc4LTQ3ZGUtNGQ4OC1iYTVmLWE5MWVhYTBjZDI5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQwNjQ5NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmFkMDk1NmY0ZTFiOGU0NTc0M2M2NDEzNWU3MmIwNmNlYjM5MzllZGE2NGNjMmNiMGUxY2Y5M2IwZDc2Y2M5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hEWNAcDIF8SxGMiqs18ZA-kPlgn63W1VHc0d2TdVPLo) 参考了一下工具箱的排版，大致这样的板块大小感觉确实没有什么好地方可以放的，感觉还是就在最下面多扩展一点来显示吧

下面的话有点看着不方便，我回头看着搞个悬浮窗吧

**Comment by Private233** [comment]
另外顺便提一嘴啊，这个新的排班表导出的时候，代码内容全在同一行了欸，像之前那样的格式方便看点吧
![image](https://github.com/Arknights-yituliu/frontend-v2-plus/assets/108540840/c96c69e3-35b6-4442-bf0b-847e329ca29c)

**Comment by yamasakura** [comment]
这个格式问题解决了，一般推荐使用编译器（比如免费的VS Code）进行修改，不然有概率会出现json格式错误（少一个,或[或{）导致无法运行，而编译器会进行格式检查，同时编译器本身一般自带添加缩进功能（也就是换行）

**Comment by yamasakura** [comment]
![QQ截图20240205122443](https://github.com/Arknights-yituliu/frontend-v2-plus/assets/84258011/b3d6da49-a4af-4416-a53d-39807608faf5)
现在我是实现了一个把鼠标移到对应干员头像上，会显示他的基建技能，你看看如何？

**Comment by Private233** [comment]
这个改动感觉很不错了，完全够用（大赞）。
但发现问题，部分干员有两个同一站的基建技能，还显示不完全（我没有全部检查，只是随意看了个别）可能会影响体验。可以考虑后续再优化一下。辛苦佬orz
![image](https://github.com/Arknights-yituliu/frontend-v2-plus/assets/108540840/c53b5d91-09f2-4ce3-a09c-e6373615da51)

**Comment by yamasakura** [comment]
忘了说了，已经解决了，就是显示的内容可能会有点多
