### ISSUE TITLE
feat: International English translation

### ISSUE THREAD

**Issue by Constrat** [Arknights-yituliu/frontend-v2-plus#29]
https://ark.yituliu.cn/tools/schedule is mainly used by MAA users. Even though the majority of the userbase can speak and understand Chinese, there's still a consistent part that can't. Are there any plans to implement a translation?
About 2 weeks ago I started trying to translate whatever I could on the page, but noticed a lot of resources came from other directories and couldn't be easily translated.

**Comment by yamasakura** [comment]
Can you explain or point which part is hard to understand/translate in resources

**Comment by Constrat** [comment]
I've never got to work with Vue so I'm a bit clueless in implementing a scalable language localisation regarding the various items to be translated, also I noticed a big rework from the "first" schedule V2 that made me lose pretty much all translation progress, as a lot of thing were renamed / moved. Are there any intentions to change a lot of things again?
If I just send the translated base schedule (for now) the big part of translating should be done. The only thing missing is having a drop-down that allows to select the language, and a way to have it scalable

**Comment by yamasakura** [comment]
Sorry for the loss of translation progress due to the refactoring of scheduleV2, because the old UI is difficult to maintain, so the refactoring. Can you submit the translated content to the warehouse through pull requests? I will try to merge it into the current branch

**Comment by Constrat** [comment]
I'll clean it up and then open a PR

**Comment by yamasakura** [comment]
Thank you very much for your translation. Do you have any idea to maintain the translation in the long term? If so, is it convenient to provide a communication method (or use any communication software)

**Comment by Constrat** [comment]
That's a nice question. Unfortunately, I don't know Chinese, so the translation is mainly a combination of Google + DeepL + knowledge of the game interfaces in both Official and International client. I had a bit of experience working in the MAA team.
When I have free time I can definitely take a look at the resources that still need to be translated.

**Comment by Constrat** [comment]
I finished my exams. I'll start working on the PR

**Comment by yamasakura** [comment]
In recent days, because of the Spring Festival, I have to go out often, it is not convenient to write code, and I will merge it in a few days

**Comment by yamasakura** [comment]
Thank you very much for your pr, now I have merged it into the branch and it is working properly

**Comment by Constrat** [comment]
Checked the latest commits:
- Clicking the language icon doesn't do anything
- Room filtering not displaying correctly. I tried implement the `translate` from i18n.js but I couldn't make it work (I hate .js)
- Not enough space between the bottom and the operator list (EN texts might be longer then the original CN)
![image](https://github.com/Arknights-yituliu/frontend-v2-plus/assets/56174894/d83d771f-cb15-4997-a1e2-67dd4590e3b9)

**Comment by yamasakura** [comment]
Sorry, I have a file modification that was not committed, so you are running an incomplete project

**Comment by Constrat** [comment]
Oh, no worries. We are all working on `dev` either way so no risk of going live

**Comment by Constrat** [comment]
Being worked on by me.
