### ISSUE TITLE
建议生成的基建文件，能自动换行。

### ISSUE THREAD

**Issue by 809717330** [Arknights-yituliu/frontend-v2-plus#30]
建议生成的基建文件，能自动换行。太乱了，生成出来的代码一坨。。。完全看不出来是啥。

**Comment by Private233** [comment]
目前来看生成的文件虽然格式捞了不方便看，但是完全能正常使用运行，网站里面编辑好就行了。后续再看佬们怎么改吧

**Comment by yamasakura** [comment]
换行后续会加回去

**Comment by yamasakura** [comment]
已经加回去了，但是推荐使用编译器（比如免费的VS Code）进行修改，不然有概率会出现json格式错误（少一个,或[或{）导致无法运行，而编译器会进行格式检查，同时编译器本身一般自带添加缩进功能（也就是换行）
