### ISSUE TITLE
建议干员练度调查中的排序方式添加按等级排序

### ISSUE THREAD

**Issue by MTXlazhu** [Arknights-yituliu/frontend-v2-plus#31]
![1234](https://github.com/Arknights-yituliu/frontend-v2-plus/assets/126753243/5db45e6f-79ac-4938-86c6-47acb638741f)
* **我希望在这个地方加上按干员等级排序，我不知道这个这个工作会给你们带来什么困难，对此我并不强求，谢谢开发团队。**

## 另外我不知道这个是不是bug，新干员还是没有图标，是还没有更新吗？
![1211](https://github.com/Arknights-yituliu/frontend-v2-plus/assets/126753243/0d4731e7-702a-4880-adcc-181bfdbe265b)

**Comment by yamasakura** [comment]
这几天就别的事情要干，所以静态资源还没更新，今晚等我下班一起更新

**Comment by MTXlazhu** [comment]
> 这几天就剩下一件事了，所以静态资源尚未更新，今晚等我下班一起更新

干员按等级排序这个功能是否能实现呢？

**Comment by yamasakura** [comment]
可以实现，我看看今晚能不能改完（人刚回家），和图片一起部署下

**Comment by MTXlazhu** [comment]
> 可以实现，我看看今晚能不能改完（人刚回家），和图片一起部署下

好的，十分感谢。

**Comment by yamasakura** [comment]
不过我不太确定今晚行不行，不行的话就得明天下午了

**Comment by MTXlazhu** [comment]
> 不过我不太确定今晚行不行，不行的话就得明天下午了

我也不是很急着用，现在也很晚了，明天再做也问题不大。现在周末，你可以适当休息一下的。
