### ISSUE TITLE
排班表生成器buildingType设置失效

### ISSUE THREAD

**Issue by Xiaodx912** [Arknights-yituliu/frontend-v2-plus#33]
问题表现为如下：
导入一个252配置json，点击导出；文件buildingType为243。
修改作业描述，同时更改布局为333，导出文件；文件描述更改已同步，但buildingType仍为243。

**Comment by yamasakura** [comment]
如果你是用的新版生成器，这个问题是正常的，因为这个字段是旧版生成器字段，新版不会用这个字段，所以就没在文件写入，无视即可
