### ISSUE TITLE
排班表生成器导出的 json 文件中包含多余的 id 字段

### ISSUE THREAD

**Issue by bodayw** [Arknights-yituliu/frontend-v2-plus#40]
目测是排班表 id 字段改成了 `scheduleId` 之后，这里没有跟着改：

https://github.com/Arknights-yituliu/frontend-v2-plus/blob/6ea57be4a27760dc4de140988658faaa310a397d/src/pages/tools/schedule.page.client.vue#L591

结果导出的文件里总是有一个 `"id": 1702203342688921`，而正确的 `scheduleId` 被放在了文件最末尾。

**Comment by yamasakura** [comment]
这俩个字段，我看了一下，计划是改成id，scheduleId废弃

**Comment by bodayw** [comment]
原来如此。总之只留一个就好（
