### ISSUE TITLE
建议新排班表生成器在最后一张换班表时点击右侧箭头能够回到第一张换班表

### ISSUE THREAD

**Issue by luvleizi** [Arknights-yituliu/frontend-v2-plus#42]
在处于换班表#3时点击右侧箭头弹出了红框。希望能够在点击后回到换班表1
 ![Untitled](https://github.com/Arknights-yituliu/frontend-v2-plus/assets/107036550/e89cd66f-da2f-431a-ad8d-ba52b70db8d5)

**Comment by yamasakura** [comment]
好的，我有空改一下
