### ISSUE TITLE
艾拉被标注为“常驻干员”

### ISSUE THREAD

**Issue by SYadda** [Arknights-yituliu/frontend-v2-plus#47]
在“精二性价比”中，彩六限定六星“艾拉”被标注为“常驻干员”，而与之类似的120井干员“灰烬”和“麒麟R夜刀”都被标注为“限定干员”。
![image](https://github.com/Arknights-yituliu/frontend-v2-plus/assets/90630675/ec0f6bee-2944-42e9-a0e8-550a710e0472)

**Comment by SYadda** [comment]
“黍”也被标注为“常驻干员”

**Comment by yamasakura** [comment]
这块是人工标注的，漏掉了，后面会改
