### ISSUE TITLE
萌新求助：可否基于我的干员池帮我推荐生成排班表

### ISSUE THREAD

**Issue by windylaugit** [Arknights-yituliu/frontend-v2-plus#48]
入职半年萌新， 干员池差不多 2/3 左右，基建很多干员都没有， 自己也不懂基建的各种干员组合(实在学不会)。
看一图流里面有个干员练度统计， 可否基于这个 我已经有的干员池，来自动生成一个 最合适的 243 两班倒 的排班？不求最高效率，只求解放双手同时效益别太低

**Comment by Constrat** [comment]
Infrastructure scheduler is not intended to be used like this.
It's just a tool to easily create (with a nice GUI) a .json file that tells [MAA](https://github.com/MaaAssistantArknights/MaaAssistantArknights) what do to.
If you want to be lazy lazy, just directly run MAA with Auto Base. It will do everything automatically (don't expect huge production numbers), the other option is making a schedule yourself, or try to copy it from someone.
