### ISSUE TITLE
攒抽计算器能新增外服&繁中服的選項嗎

### ISSUE THREAD

**Issue by amasoiD** [Arknights-yituliu/frontend-v2-plus#54]

**Comment by yamasakura** [comment]
外服排期这边不会排QAQ，需要会排外服卡池日期的

**Comment by kai1116kai** [comment]
請問能根據官服活動未來視來排程嗎? 加註僅供參考的字樣就好，因為其他服會不會更改活動排程比較難預料，但也能讓玩家加減參考來規劃，謝謝大佬們

**Comment by yamasakura** [comment]
> 請問能根據官服活動未來視來排程嗎? 加註僅供參考的字樣就好，因為其他服會不會更改活動排程比較難預料，但也能讓玩家加減參考來規劃，謝謝大佬們

我和别的开发商量下
