### ISSUE TITLE
website not changing to English / 网站未更改为英文

### ISSUE THREAD

**Issue by coldasicee** [Arknights-yituliu/frontend-v2-plus#58]
If you click to change the language to English nothing happens.
如果点击将语言更改为英语，则什么也不会发生。
(译文 DeepL)

![Screenshot 2024-05-09 181724](https://github.com/Arknights-yituliu/frontend-v2-plus/assets/84877944/c81f699c-11f8-4614-9148-1498c6fc4507)

**Comment by yamasakura** [comment]
暂时只有基建生成器有人翻译了，别的页面没有，这个按钮属于一个显示bug，他实际上应该只在基建生成器页面显示

**Comment by coldasicee** [comment]
我明白了，谢谢你告诉我。

**Comment by Constrat** [comment]
I should start translating everything 🆘 
No time 😭
