### ISSUE TITLE
礼包性价比里面少了一个新人养成组合包

### ISSUE THREAD

**Issue by RainlightX** [Arknights-yituliu/frontend-v2-plus#59]
想看看新人养成组合包的性价比，结果没找到
![微信图片_20240517014447](https://github.com/Arknights-yituliu/frontend-v2-plus/assets/170053376/8d6a60b5-b33f-4e99-af12-9b40ad26bda4)

**Comment by yamasakura** [comment]
这个包印象中是因为好像太差了，当时就没录入他
