### ISSUE TITLE
不建议背景颜色使用#808080

### ISSUE THREAD

**Issue by 050644zf** [Arknights-yituliu/frontend-v2-plus#6]
#808080 也就是rgb(128,128,128)是黑和白的中间值，在电脑上鼠标主要以反色形式呈现，而当背景为#808080时鼠标颜色刚好也是#808080，会导致鼠标位置难以辨识

**Comment by yamasakura** [comment]
能否给一张示意图看一下，我不太清楚鼠标为什么是这个颜色？

**Comment by 050644zf** [comment]
![image](https://github.com/Arknights-yituliu/frontend-v2-plus/assets/30611816/158ff315-1f0f-4198-bea7-a115c0752a32)
录屏截取的，鼠标中心有一两个灰度值差异为视频压缩导致
