### ISSUE TITLE
练度统计疑似有坏数据

### ISSUE THREAD

**Issue by uranv** [Arknights-yituliu/frontend-v2-plus#60]
![IMG_3738](https://github.com/Arknights-yituliu/frontend-v2-plus/assets/168523312/aadb1fad-1563-4424-8025-38490206229d)
阿米娅持有率98.8%而不是100%，同时这几个四星最高同样是98.8%，疑似是有占比1.2%的空数据？还是持有率计算公式问题？

**Comment by yamasakura** [comment]
我猜测可能是有几个没导入成功的账号被标记为导入过了，我回头再加强下导入检查
