### ISSUE TITLE
贸易站找不到推进之王

### ISSUE THREAD

**Issue by sanjio-pv** [Arknights-yituliu/frontend-v2-plus#63]
![无标题](https://github.com/Arknights-yituliu/frontend-v2-plus/assets/172530970/23f0bbab-5e8d-41ae-96f3-46a59f95d573)

**Comment by yamasakura** [comment]
应该是筛选有点小问题，最近代码分支合并的有点乱

**Comment by bodayw** [comment]
这个应该是因为推进之王**本身**的基建技能都是在宿舍生效的，选中贸易站时只会把有在贸易站生效技能的人筛选出来。

我前几天把这个筛选表补充了一下，现在`特殊组合`这个里面专门有一个`格拉斯哥帮`，可以把和摩根以及戴菲恩绑定的相关干员都列出来。

类似地，选中制造站时也是不会列出那几个深海猎人的，但可以选`特殊组合`里的`深海猎人`，会把相关的人（包括歌蕾蒂娅）都列出来。同理，你如果想在宿舍里塞几个莱茵生命的人来提高缪尔赛思在发电站造无人机的效率，点宿舍是找不到人的，但是你可以点`特殊组合`里的`莱茵生命`。

**Comment by bodayw** [comment]
又想了一下，或许可以这样：在搜索框输入干员名 / 技能名 / 技能描述的时候，搜索范围扩大到全部干员，而不是只在当前选中的分类内搜索。

因为用户手动输入关键字的时候，心里应该已经有比较明确目标，感觉上“全局”搜索更符合直觉。
