### ISSUE TITLE
一点小小的建议

### ISSUE THREAD

**Issue by JohnHe327** [Arknights-yituliu/frontend-v2-plus#7]
一个是目前来看理想城应该是在今年夏活后复刻了，感觉可以加个提示什么的
一个是能不能在其他资源估算里加一下历史限时礼包的选项，比如写一个45档零钱包，一个68档手提箱这样，然后把上次该档的资源写上。我印象里手提箱一直是有70万lmb，每次换汤不换药但实在记不清每档都有啥（（而且我记得之前性价比上是有历史礼包的，但这次好像没找到，然后又去b站找上次活动的礼包攻略，也不好算抽

**Comment by yamasakura** [comment]
历史礼包有这个计划，但是近期没有时间调整
