### ISSUE TITLE
可视化排班中会客室的干员列表少了斥罪

### ISSUE THREAD

**Issue by conse7** [Arknights-yituliu/frontend-v2-plus#73]
![image](https://github.com/user-attachments/assets/6542b11d-ae0e-436f-bc93-766b635fa15b)

**Comment by yamasakura** [comment]
斥罪是在办公室的，加速招募的 
“进驻人力办公室时，人脉资源的联络速度+50%，心情每小时消耗+0.5”
你选择的是会客室，搜集线索那个
