### ISSUE TITLE
基建排班识别问题

### ISSUE THREAD

**Issue by siestajzf** [Arknights-yituliu/frontend-v2-plus#75]
基建排班下的辅助小车和重装小车好像ocr识别不了，会陷入寻找的死循环

**Comment by siestajzf** [comment]
对比了一下小号，辅助小车和重装是能正常识别选中的，这问题感觉有点奇怪

**Comment by yamasakura** [comment]
识别问题需要去maa仓库那边进行反馈，一图流仅提供了一个排班表，识别问题无能为力。
