### ISSUE TITLE
UI与功能不匹配：干员练度调查-筛选/批量操作-是否拥有 已拥有 未拥有

### ISSUE THREAD

**Issue by chanchancl** [Arknights-yituliu/frontend-v2-plus#76]
是否拥有
* 已拥有
* 未拥有

这两个按键的功能和显示的UI文字相反
例如，我没有烈夏、兔头、和渡桥 这三个五星，
但只有当我点“已拥有”的时候，才能筛选出这三个

如图：
![image](https://github.com/user-attachments/assets/44c56a4d-018b-414a-b50b-e673e4313a3f)

**Comment by yamasakura** [comment]
已修复
