### ISSUE TITLE
干员练度调查结果不显示干员名称+精二率排序失效

### ISSUE THREAD

**Issue by BeiChen2015** [Arknights-yituliu/frontend-v2-plus#78]
2024-7-30的网站版本，干员练度调查结果，不再显示干员名称，而上一版是有的。没有干员名称对于新手来说实在难看懂，无法知道头像是哪个干员。希望能再加回来干员名称。
另外点击精二率排序也不好使了，其它排序正常。

**Comment by yamasakura** [comment]
名称显示已加回，精英率排序也已修复
