### ISSUE TITLE
官网和森空岛导入干员练度失败

### ISSUE THREAD

**Issue by ykw-9826** [Arknights-yituliu/frontend-v2-plus#97]
显示官网未授权和森空岛未登入，服务器是b服，上个月还能用

![image](https://github.com/user-attachments/assets/7bb6339a-ae24-40eb-bda5-dd47247416db)
![image](https://github.com/user-attachments/assets/81c4c850-9e88-49af-95b1-25310343f9be)

**Comment by yamasakura** [comment]
森空岛的接口升级了防爬，暂时用不了
