### ISSUE TITLE
希望增加使用菲亚梅塔交换体力能对多个干员筛选并选出最低精力的一位

### ISSUE THREAD

**Issue by quarx613** [Arknights-yituliu/frontend-v2-plus#98]
希望增加使用菲亚梅塔交换体力能对多个干员筛选并选出最低精力的一位 比如龙舌兰巫恋 2选1时选择低精力的一位

**Comment by yamasakura** [comment]
这个需要MAA那边提供功能支持，可以去MAA那边给他们也提一下issues，这边只能根据他们已有的功能进行协议的生成

[MAA的Issues区](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues)
